### ISSUE TITLE
Can't startup the app runner home

### ISSUE THREAD

**Issue by chancein007** [danielflower/app-runner#16]
After downloading the source code and had tried to startup the app runner home, it hints the below error message. It seems that the Maven runner doesn't work. 
Could you kindly us on how to configure the Maven and Java provider?

com.danielflower.apprunner.runners.UnsupportedProjectTypeException: No app runner found for app-runner-home
	at com.danielflower.apprunner.runners.AppRunnerFactoryProvider.runnerFor(AppRunnerFactoryProvider.java:54)
	at com.danielflower.apprunner.AppEstate.addApp(AppEstate.java:63)
	at com.danielflower.apprunner.App.start(App.java:71)
	at com.danielflower.apprunner.App.main(App.java:191)
	at com.danielflower.apprunner.RunLocal.main(RunLocal.java:10)

**Comment by danielflower** [comment]
AppRunner just uses whatever tools are on your path unless specifically configured. So do you have mvn on the path? Maven may need M2_HOME env var set too.
